import pandas as pd
from datetime import datetime
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter
from openpyxl.comments import Comment

products = pd.read_csv("products.csv")
weekly = pd.read_csv("weekly_panel.csv")
market = pd.read_csv("market_weekly.csv")
reviews = pd.read_csv("reviews.csv")

for df, cols in [(products, ["launch_week"]), (weekly, ["week_start"]),
                 (market, ["week_start"]), (reviews, ["week_start"])]:
    for c in cols:
        df[c] = pd.to_datetime(df[c])

F = "Arial"
BASE = Font(name=F, size=10)
BOLD = Font(name=F, size=10, bold=True)
HEAD = Font(name=F, size=10, bold=True, color="FFFFFF")
TITLE = Font(name=F, size=14, bold=True)
BLUE = Font(name=F, size=10, color="0000FF")
GREY_NOTE = Font(name=F, size=9, italic=True, color="666666")
FILL_HEAD = PatternFill("solid", start_color="4B1248")
FILL_HIDDEN = PatternFill("solid", start_color="8C8C8C")
FILL_HELPER = PatternFill("solid", start_color="1F6F5C")
FILL_INPUT = PatternFill("solid", start_color="FFFF00")
FILL_SECTION = PatternFill("solid", start_color="EFE6F0")
THIN = Border(bottom=Side(style="thin", color="CCCCCC"))

wb = Workbook()

# ------------------------------------------------------------------ README
ws = wb.active
ws.title = "README"
lines = [
    ("Price Confidence - synthetic listing dataset", TITLE),
    ("Team Edge Case, IIT Roorkee - Meesho DICE Challenge S3", BASE),
    ("", BASE),
    ("THIS DATA IS SYNTHETIC. It was generated by generate_dataset.py (seed 20260930) from assumed buyer "
     "behaviour. It demonstrates the pricing method; it is not evidence about real Meesho buyers.", BOLD),
    ("", BASE),
    ("What is inside", BOLD),
    ("Products: 150 soap + 150 t-shirt listings, one row each. Launch weeks from 1 Sep 2025 to 3 Aug 2026.", BASE),
    ("Weekly_Panel: one row per listing per live week, from launch to the week of 21 Sep 2026 (or until delisted).", BASE),
    ("Market_Weekly: platform-wide category reference per week (median, p25, p75 price, demand index, festival and campaign flags).", BASE),
    ("Reviews: one row per review with stars, sentiment, theme (praise / mixed / price / quality) and comment text.", BASE),
    ("Quick_Checks: formula-driven summaries to sanity-check the data.", BASE),
    ("Data_Dictionary: every column explained, and whether Meesho could observe it in real life.", BASE),
    ("", BASE),
    ("Column colour code", BOLD),
    ("Purple header = observable data Meesho would hold. Grey header (hidden_*) = known only because the data is "
     "synthetic; use for evaluation and backtesting, never as a model input. Green header = helper formula column.", BASE),
    ("", BASE),
    ("Key assumptions (all team assumptions unless stated)", BOLD),
    ("Forward shipping: Rs 30 per soap, Rs 70 per t-shirt (fixed by the team for the demo).", BASE),
    ("Reverse shipping on a customer return = the forward fee. RTO parcels return intact at no extra charge; forward fee is lost.", BASE),
    ("Returned soap cannot be resold. About 70% of returned t-shirts go back to stock.", BASE),
    ("GST 5% on both categories. Listing price includes GST.", BASE),
    ("Festival and campaign weeks are an illustrative calendar, not Meesho's actual sale dates.", BASE),
    ("Hidden drivers: true product quality, seller cost, seller strategy (investment / market / premium / cost-plus) "
     "and a launch budget. Search exposure grows with conversion, review count and rating, so early sales feed later visibility.", BASE),
    ("Sellers may give up (delist) when orders dry up or losses exceed their budget, so failed listings stay in the data.", BASE),
    ("", BASE),
    ("Profit definition (hidden_contribution_inr)", BOLD),
    ("kept orders x selling price / 1.05  -  forward shipping on every order  -  reverse shipping on returns  -  "
     "unit cost on stock not recovered  -  free gift per order.", BASE),
]
for i, (t, f) in enumerate(lines, start=1):
    c = ws.cell(row=i, column=1, value=t)
    c.font = f
    c.alignment = Alignment(wrap_text=True, vertical="top")
ws.column_dimensions["A"].width = 130

# ------------------------------------------------------------------ data sheets
def write_df(ws, df, hidden_prefix="hidden_", fmt=None, widths=None):
    fmt = fmt or {}
    for j, col in enumerate(df.columns, start=1):
        c = ws.cell(row=1, column=j, value=col)
        c.font = HEAD
        c.fill = FILL_HIDDEN if col.startswith(hidden_prefix) else FILL_HEAD
        c.alignment = Alignment(wrap_text=True, vertical="center")
    for i, row in enumerate(df.itertuples(index=False), start=2):
        for j, v in enumerate(row, start=1):
            if pd.isna(v):
                v = None
            elif hasattr(v, "to_pydatetime"):
                v = v.to_pydatetime()
            c = ws.cell(row=i, column=j, value=v)
            c.font = BASE
            col = df.columns[j - 1]
            if col in fmt:
                c.number_format = fmt[col]
    ws.freeze_panes = "B2"
    for j, col in enumerate(df.columns, start=1):
        ws.column_dimensions[get_column_letter(j)].width = (widths or {}).get(col, max(10, min(26, len(col) + 2)))
    ws.row_dimensions[1].height = 30


DATE = "yyyy-mm-dd"
INR = "#,##0;(#,##0);-"
INR2 = "#,##0.00;(#,##0.00);-"

wsP = wb.create_sheet("Products")
write_df(wsP, products, fmt={"launch_week": DATE, "launch_price": INR, "platform_median_at_launch": INR,
                             "current_listing_price": INR, "hidden_unit_cost_inr": INR2,
                             "hidden_free_gift_inr": INR2, "hidden_launch_budget_inr": INR,
                             "hidden_cumulative_contribution_inr": INR, "launch_vs_median": "0.000"})
wsW = wb.create_sheet("Weekly_Panel")
write_df(wsW, weekly, fmt={"week_start": DATE, "listing_price": INR, "selling_price": INR,
                           "discount_pct": "0%", "hidden_contribution_inr": INR2})
wsM = wb.create_sheet("Market_Weekly")
write_df(wsM, market, fmt={"week_start": DATE, "platform_median_price": INR, "platform_p25_price": INR,
                           "platform_p75_price": INR})
wsR = wb.create_sheet("Reviews")
write_df(wsR, reviews, fmt={"week_start": DATE}, widths={"comment": 42})

# column letters we need for formulas
def col_of(df, name):
    return get_column_letter(list(df.columns).index(name) + 1)

nP, nW, nM = len(products) + 1, len(weekly) + 1, len(market) + 1
P = {c: col_of(products, c) for c in products.columns}
W = {c: col_of(weekly, c) for c in weekly.columns}
M = {c: col_of(market, c) for c in market.columns}

def wrange(c):
    return f"Weekly_Panel!${W[c]}$2:${W[c]}${nW}"

def prange(c):
    return f"Products!${P[c]}$2:${P[c]}${nP}"

def mrange(c):
    return f"Market_Weekly!${M[c]}$2:${M[c]}${nM}"

# helper formula columns on Products
helpers = ["eligible_12w", "survived_12w", "orders_first_12w", "hidden_profit_first_12w", "rating_group"]
start = len(products.columns) + 1
H = {h: get_column_letter(start + k) for k, h in enumerate(helpers)}
for k, h in enumerate(helpers):
    c = wsP.cell(row=1, column=start + k, value=h)
    c.font = HEAD
    c.fill = FILL_HELPER
    c.alignment = Alignment(wrap_text=True, vertical="center")
    wsP.column_dimensions[H[h]].width = 16
wsP.cell(row=1, column=start).comment = Comment(
    "1 if the listing launched early enough to have 12 weeks of data by 21 Sep 2026 (cutoff on Quick_Checks).", "Team Edge Case")
for i in range(2, nP + 1):
    pid = f"$A{i}"
    wsP[f"{H['eligible_12w']}{i}"] = f"=IF({P['launch_week']}{i}<=Quick_Checks!$C$5,1,0)"
    wsP[f"{H['survived_12w']}{i}"] = f"=IF(AND({H['eligible_12w']}{i}=1,{P['weeks_live']}{i}>=12),1,0)"
    wsP[f"{H['orders_first_12w']}{i}"] = (f"=SUMIFS({wrange('orders_placed')},{wrange('product_id')},{pid},"
                                          f"{wrange('week_num')},\"<=12\")")
    wsP[f"{H['hidden_profit_first_12w']}{i}"] = (f"=SUMIFS({wrange('hidden_contribution_inr')},{wrange('product_id')},{pid},"
                                                 f"{wrange('week_num')},\"<=12\")")
    wsP[f"{H['rating_group']}{i}"] = (f"=IF({P['final_rating']}{i}=\"\",\"no reviews\","
                                      f"IF({P['final_rating']}{i}>=Quick_Checks!$C$6,\"good\",\"weak\"))")
    for h in helpers:
        wsP[f"{H[h]}{i}"].font = BASE
    wsP[f"{H['hidden_profit_first_12w']}{i}"].number_format = INR

# ------------------------------------------------------------------ Quick_Checks
wq = wb.create_sheet("Quick_Checks", 1)
wq.column_dimensions["A"].width = 3
wq.column_dimensions["B"].width = 34
for col in "CDEFGHIJKLMN":
    wq.column_dimensions[col].width = 14

def put(cell, v, font=BASE, fmt=None, fill=None, align=None):
    wq[cell] = v
    wq[cell].font = font
    if fmt:
        wq[cell].number_format = fmt
    if fill:
        wq[cell].fill = fill
    if align:
        wq[cell].alignment = align

put("B1", "Quick checks (all numbers below are formulas over the data sheets)", TITLE)
put("B3", "Inputs (yellow = change freely)", BOLD)
put("B5", "Cutoff launch week for 12-week cohorts")
put("C5", datetime(2026, 7, 6), BLUE, DATE, FILL_INPUT)
put("D5", "Latest launch that still has 12 weeks of data by 21 Sep 2026", GREY_NOTE)
put("B6", "Rating that counts as a 'good' product")
put("C6", 3.8, BLUE, "0.0", FILL_INPUT)
put("B7", "Current period starts (last 4 weeks)")
put("C7", datetime(2026, 8, 31), BLUE, DATE, FILL_INPUT)
put("B8", "Previous period starts (4 weeks before)")
put("C8", datetime(2026, 8, 3), BLUE, DATE, FILL_INPUT)
put("D8", "Previous period runs to the day before C7", GREY_NOTE)

cats = ["soap", "tshirt"]
hdr = lambda r, cols: [put(f"{get_column_letter(3 + k)}{r}", t, HEAD, fill=FILL_HEAD,
                           align=Alignment(wrap_text=True, horizontal="center")) for k, t in enumerate(cols)]

# 1. Listings
r = 10
put(f"B{r}", "1. Listings", BOLD, fill=FILL_SECTION)
hdr(r + 1, ["Listings", "Active", "Delisted", "Delisted %", "Avg launch price", "Avg final rating", "Avg reviews"])
for k, cat in enumerate(cats):
    rr = r + 2 + k
    put(f"B{rr}", cat, BOLD)
    put(f"C{rr}", f"=COUNTIFS({prange('category')},$B{rr})")
    put(f"D{rr}", f"=COUNTIFS({prange('category')},$B{rr},{prange('status')},\"active\")")
    put(f"E{rr}", f"=COUNTIFS({prange('category')},$B{rr},{prange('status')},\"delisted\")")
    put(f"F{rr}", f"=IFERROR(E{rr}/C{rr},0)", fmt="0.0%")
    put(f"G{rr}", f"=AVERAGEIFS({prange('launch_price')},{prange('category')},$B{rr})", fmt=INR)
    put(f"H{rr}", f"=AVERAGEIFS({prange('final_rating')},{prange('category')},$B{rr})", fmt="0.00")
    put(f"I{rr}", f"=AVERAGEIFS({prange('review_count')},{prange('category')},$B{rr})", fmt="0.0")

# 2. Funnel
r = 16
put(f"B{r}", "2. Buyer funnel, all weeks", BOLD, fill=FILL_SECTION)
fcols = ["impressions", "product_views", "add_to_cart", "orders_placed", "rto_orders", "delivered_orders",
         "customer_returns", "kept_orders"]
hdr(r + 1, ["Impressions", "Views", "Add to cart", "Orders", "RTO", "Delivered", "Returns", "Kept"])
for k, cat in enumerate(cats):
    rr = r + 2 + k
    put(f"B{rr}", cat, BOLD)
    for j, fc in enumerate(fcols):
        put(f"{get_column_letter(3 + j)}{rr}", f"=SUMIFS({wrange(fc)},{wrange('category')},$B{rr})", fmt="#,##0")
r = 21
hdr(r, ["Views / impr.", "Cart / views", "Orders / views", "RTO / orders", "Returns / delivered", "Kept / orders"])
for k, cat in enumerate(cats):
    rr = r + 1 + k
    s = 18 + k
    put(f"B{rr}", f"{cat} rates", BOLD)
    put(f"C{rr}", f"=IFERROR(D{s}/C{s},0)", fmt="0.0%")
    put(f"D{rr}", f"=IFERROR(E{s}/D{s},0)", fmt="0.0%")
    put(f"E{rr}", f"=IFERROR(F{s}/D{s},0)", fmt="0.0%")
    put(f"F{rr}", f"=IFERROR(G{s}/F{s},0)", fmt="0.0%")
    put(f"G{rr}", f"=IFERROR(I{s}/H{s},0)", fmt="0.0%")
    put(f"H{rr}", f"=IFERROR(J{s}/F{s},0)", fmt="0.0%")

# 3. Launch cohorts
r = 25
put(f"B{r}", "3. Launch cohorts: first 12 weeks (listings launched on or before C5)", BOLD, fill=FILL_SECTION)
put(f"B{r + 1}", "Averages are pulled up by a few big winners; read with the listing count.", GREY_NOTE)
hdr(r + 2, ["Listings", "Survived to wk 12", "Survival %", "Avg orders, wk 1-12", "Avg profit, wk 1-12 (hidden)"])
rr = r + 3
for cat in cats:
    for grp in ["good", "weak"]:
        for pos in ["below", "at", "above"]:
            put(f"B{rr}", f"{cat} | {grp} | launched {pos}", BASE)
            crit = (f"{prange('category')},\"{cat}\",{prange('launch_position')},\"{pos}\","
                    f"Products!${H['rating_group']}$2:${H['rating_group']}${nP},\"{grp}\","
                    f"Products!${H['eligible_12w']}$2:${H['eligible_12w']}${nP},1")
            put(f"C{rr}", f"=COUNTIFS({crit})")
            put(f"D{rr}", f"=COUNTIFS({crit},Products!${H['survived_12w']}$2:${H['survived_12w']}${nP},1)")
            put(f"E{rr}", f"=IFERROR(D{rr}/C{rr},\"-\")", fmt="0%")
            put(f"F{rr}", f"=IFERROR(AVERAGEIFS(Products!${H['orders_first_12w']}$2:${H['orders_first_12w']}${nP},{crit}),\"-\")",
                fmt="#,##0")
            put(f"G{rr}", f"=IFERROR(AVERAGEIFS(Products!${H['hidden_profit_first_12w']}$2:${H['hidden_profit_first_12w']}${nP},{crit}),\"-\")",
                fmt=INR)
            rr += 1

# 4. Current trend
r = rr + 1
put(f"B{r}", "4. Current market trend (platform-wide, Market_Weekly)", BOLD, fill=FILL_SECTION)
hdr(r + 1, ["Median price, prev 4 wks", "Median price, last 4 wks", "Change", "Demand index, prev 4 wks",
            "Demand index, last 4 wks", "Change"])
for k, cat in enumerate(cats):
    rr = r + 2 + k
    put(f"B{rr}", cat, BOLD)
    prev = f"{mrange('category')},$B{rr},{mrange('week_start')},\">=\"&$C$8,{mrange('week_start')},\"<\"&$C$7"
    last = f"{mrange('category')},$B{rr},{mrange('week_start')},\">=\"&$C$7"
    put(f"C{rr}", f"=AVERAGEIFS({mrange('platform_median_price')},{prev})", fmt=INR)
    put(f"D{rr}", f"=AVERAGEIFS({mrange('platform_median_price')},{last})", fmt=INR)
    put(f"E{rr}", f"=IFERROR(D{rr}/C{rr}-1,0)", fmt="+0.0%;-0.0%")
    put(f"F{rr}", f"=AVERAGEIFS({mrange('category_demand_index')},{prev})", fmt="0.00")
    put(f"G{rr}", f"=AVERAGEIFS({mrange('category_demand_index')},{last})", fmt="0.00")
    put(f"H{rr}", f"=IFERROR(G{rr}/F{rr}-1,0)", fmt="+0.0%;-0.0%")
wq.freeze_panes = "C3"

# ------------------------------------------------------------------ Data dictionary
wd = wb.create_sheet("Data_Dictionary", 2)
dd = [
    ("Products", "product_id", "Listing ID (SP = soap, TS = t-shirt)", "Yes"),
    ("Products", "category", "soap or tshirt", "Yes"),
    ("Products", "title", "Listing title", "Yes"),
    ("Products", "launch_week", "Week the listing went live", "Yes"),
    ("Products", "launch_price", "Listing price in week 1 (Rs, incl. GST)", "Yes"),
    ("Products", "platform_median_at_launch", "Category median price across the platform in the launch week", "Yes"),
    ("Products", "launch_vs_median", "launch_price / platform median", "Yes"),
    ("Products", "launch_position", "below (< 0.94x median), at, or above (> 1.06x median)", "Yes"),
    ("Products", "listing_quality_score", "Photo and listing completeness score, 0-100", "Yes"),
    ("Products", "current_listing_price", "Latest listing price", "Yes"),
    ("Products", "status / delist_week / weeks_live", "Whether the listing is still live, and for how long", "Yes"),
    ("Products", "total_* / review_count / final_rating", "Lifetime totals from Weekly_Panel", "Yes"),
    ("Products", "hidden_unit_cost_inr", "Seller's material + packaging cost per unit", "No - seller-private"),
    ("Products", "hidden_free_gift_inr", "Free gift put in every parcel (like Seller 6's free bar)", "No - seller-private"),
    ("Products", "hidden_seller_strategy", "investment / market / premium / cost_plus_stale", "No - generator only"),
    ("Products", "hidden_true_quality", "True product quality driver (z-score)", "No - generator only"),
    ("Products", "hidden_launch_budget_inr", "Loss the seller would tolerate before giving up", "No - seller-private"),
    ("Products", "hidden_cumulative_contribution_inr", "Lifetime profit using the seller's true costs", "No - needs seller cost"),
    ("Products", "eligible_12w ... rating_group", "Helper formulas used by Quick_Checks", "Derived"),
    ("Weekly_Panel", "week_start / week_num", "Monday of the week; weeks since launch (1 = launch week)", "Yes"),
    ("Weekly_Panel", "listing_price / discount_pct / selling_price", "Price set, campaign discount, and price the buyer paid", "Yes"),
    ("Weekly_Panel", "festival_week / campaign_week", "Calendar flags", "Yes"),
    ("Weekly_Panel", "impressions", "Times the listing was shown in feed or search", "Yes"),
    ("Weekly_Panel", "product_views", "Times the product page was opened (clicks)", "Yes"),
    ("Weekly_Panel", "wishlist_adds / add_to_cart", "Intent signals", "Yes"),
    ("Weekly_Panel", "orders_placed / cod_orders", "Orders (buyers) and how many were cash on delivery", "Yes"),
    ("Weekly_Panel", "rto_orders", "Returned to origin: buyer refused or was unreachable", "Yes"),
    ("Weekly_Panel", "delivered_orders / customer_returns / kept_orders", "delivered = orders - RTO; kept = delivered - returns", "Yes"),
    ("Weekly_Panel", "return_<reason>", "Returns split by reason (size, quality, not as pictured, damaged, wrong item, changed mind)", "Yes"),
    ("Weekly_Panel", "returns_resold", "Returned units put back into stock", "Yes"),
    ("Weekly_Panel", "new_reviews ... neg_quality_mentions", "Reviews that week, their stars, sentiment, and whether negatives mention price or quality", "Yes"),
    ("Weekly_Panel", "cumulative_reviews / cumulative_rating", "Rating shown to buyers at the end of the week", "Yes"),
    ("Weekly_Panel", "hidden_contribution_inr", "That week's profit using the seller's true costs", "No - needs seller cost"),
    ("Market_Weekly", "platform_median / p25 / p75 price", "Category price reference across ALL listings on the platform", "Yes"),
    ("Market_Weekly", "category_demand_index", "Category demand vs normal (1.00 = normal week)", "Yes"),
    ("Reviews", "stars / sentiment / theme / comment", "One row per review; theme splits negatives into price vs quality", "Yes"),
    ("Reviews", "from_returned_order", "1 if the reviewer returned the item", "Yes"),
]
for j, t in enumerate(["Sheet", "Column", "Meaning", "Observable to Meesho?"], start=1):
    c = wd.cell(row=1, column=j, value=t)
    c.font = HEAD
    c.fill = FILL_HEAD
for i, row in enumerate(dd, start=2):
    for j, v in enumerate(row, start=1):
        c = wd.cell(row=i, column=j, value=v)
        c.font = BASE
        c.alignment = Alignment(wrap_text=True, vertical="top")
for col, wdt in zip("ABCD", [15, 42, 80, 22]):
    wd.column_dimensions[col].width = wdt
wd.freeze_panes = "A2"

wb.save("Price_Confidence_Synthetic_Dataset.xlsx")
print("saved")
